name: Bot DataRedonda Network Sniffer

on:
  schedule:
    # Se ejecuta a las 10:13 UTC (7:13 AM hora de Argentina) para evitar la fila de espera de GitHub
    - cron: '0 11 * * *'
  workflow_dispatch: # Permite que también lo puedas ejecutar manualmente cuando quieras

jobs:
  run-bot:
    runs-on: ubuntu-22.04

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias y Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium --with-deps

      - name: Ejecutar script de captura
        run: python capturar.py

      - name: Commitear y subir resultados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f partidos_live.json ]; then
            git add partidos_live.json
            git commit -m "Actualización automática de partidos" || exit 0
            git push
          else
            echo "No se generó el archivo partidos_live.json en esta ejecución."
          fi
